
ALGORITHM:
  NAME: "GOLEM"
  LAMBDA_1: 0.02
  LAMBDA_2: 5.0
  EQUAL_VARIANCE: True
  NUM_ITER: 1000
  LR: 0.001
  SEED: 1
  CHECKPOINT_ITER: 5000
  B_INIT: None 
THRESOLDING: 0.3 

DATASET:
  NAME: "default"
  DATA_PATH: "/dataset/Bayesian_Data/ASIA/ASIA_DATA.csv"
  GT_PATH: "/dataset/Bayesian_Data/ASIA/DAGtrue_ASIA_bi.csv" 
RESULT_PATH: '/workspace/tripx/projects/causality/notears/W_est.xls'

